// Auto-generated by scripts/download-met-icons.mjs — do not edit by hand.
import type { ArtworkAttribution } from './types';

export type IconPoolEntry = {
  src: string;
  title: string;
  author: string;
  medium?: string;
  license: string;
  sourceUrl: string;
  detailSrc?: string;
};

export const fixedIcons: Record<string, string> = {
  "gray-catbird": "/icons/gray-catbird.jpg",
  "northern-cardinal": "/icons/northern-cardinal.jpg",
  "blue-jay": "/icons/blue-jay.jpg",
  "tui": "/icons/tui.jpg",
  "bellbird": "/icons/bellbird.jpg",
  "morepork": "/icons/morepork.jpg",
  "fantail": "/icons/fantail.jpg",
  "gull": "/icons/gull.jpg",
  "howler": "/icons/howler.jpg",
  "insects": "/icons/insects.jpg"
};

export const iconPools: Record<string, IconPoolEntry[]> = {
  "surf": [
    {
      "src": "/icons/met/11908.jpg",
      "title": "Good Harbor Beach, Cape Ann, Massachusetts",
      "author": "William Trost Richards",
      "medium": "Graphite on tan wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/11908"
    },
    {
      "src": "/icons/met/17053.jpg",
      "title": "Boys in a Dory",
      "author": "Winslow Homer",
      "medium": "Watercolor and gouache over graphite",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/17053"
    },
    {
      "src": "/icons/met/339153.jpg",
      "title": "Fishing Boats on the Beach in Winter",
      "author": "Anton Mauve",
      "medium": "Black chalk, watercolor, and white bodycolor",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/339153"
    },
    {
      "src": "/icons/met/334086.jpg",
      "title": "On the Beach",
      "author": "Eugène Boudin",
      "medium": "Graphite and watercolor",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/334086"
    },
    {
      "src": "/icons/met/460052.jpg",
      "title": "Beach Scene",
      "author": "Eugène Boudin",
      "medium": "Pastel on gray wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/460052"
    },
    {
      "src": "/icons/met/15519.jpg",
      "title": "Bay, Hill, and Figure on Shore (from Sketchbook X)",
      "author": "William Trost Richards",
      "medium": "Graphite on off-white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/15519"
    }
  ],
  "wind": [
    {
      "src": "/icons/met/824771.jpg",
      "title": "Marie Antoinette in a Park",
      "author": "Anonymous (French)",
      "medium": "Black chalk, stumped, and white chalk",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/824771"
    },
    {
      "src": "/icons/met/11306.jpg",
      "title": "Birch Tree, Niagara",
      "author": "John Frederick Kensett",
      "medium": "Graphite on smooth textured off-white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/11306"
    },
    {
      "src": "/icons/met/11124.jpg",
      "title": "Hurricane, Bahamas",
      "author": "Winslow Homer",
      "medium": "Watercolor and graphite on off-white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/11124"
    }
  ],
  "forest": [
    {
      "src": "/icons/met/10378.jpg",
      "title": "Forest Scene",
      "author": "Johann Hermann Carmiencke",
      "medium": "Graphite and watercolor on buff-colored wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/10378"
    },
    {
      "src": "/icons/met/11306.jpg",
      "title": "Birch Tree, Niagara",
      "author": "John Frederick Kensett",
      "medium": "Graphite on smooth textured off-white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/11306"
    },
    {
      "src": "/icons/met/15775.jpg",
      "title": "Two Sketches: River Bank with Trees; Figure in a Canoe",
      "author": "Albert Bierstadt",
      "medium": "Graphite on wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/15775"
    }
  ],
  "rain": [
    {
      "src": "/icons/met/11124.jpg",
      "title": "Hurricane, Bahamas",
      "author": "Winslow Homer",
      "medium": "Watercolor and graphite on off-white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/11124"
    },
    {
      "src": "/icons/met/13115.jpg",
      "title": "New York from the Heights near Brooklyn",
      "author": "William Guy Wall",
      "medium": "Watercolor and graphite on white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/13115"
    },
    {
      "src": "/icons/met/489985.jpg",
      "title": "Rain Landscape",
      "author": "Vasily Kandinsky",
      "medium": "Watercolor over graphite on paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/489985"
    }
  ],
  "stream": [
    {
      "src": "/icons/met/15775.jpg",
      "title": "Two Sketches: River Bank with Trees; Figure in a Canoe",
      "author": "Albert Bierstadt",
      "medium": "Graphite on wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/15775"
    },
    {
      "src": "/icons/met/17053.jpg",
      "title": "Boys in a Dory",
      "author": "Winslow Homer",
      "medium": "Watercolor and gouache over graphite",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/17053"
    },
    {
      "src": "/icons/met/15519.jpg",
      "title": "Bay, Hill, and Figure on Shore (from Sketchbook X)",
      "author": "William Trost Richards",
      "medium": "Graphite on off-white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/15519"
    }
  ],
  "quetzal": [
    {
      "src": "/icons/met/338617.jpg",
      "title": "Long-Tailed Bird Seen in Profile",
      "author": "Count Giorgio Durante (Duranti)",
      "medium": "Watercolor over graphite",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/338617"
    },
    {
      "src": "/icons/met/363843.jpg",
      "title": "Eclectus Roratus Polychloros",
      "author": "Edward Lear",
      "medium": "Watercolor and gouache over graphite",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/363843"
    }
  ],
  "toucan": [
    {
      "src": "/icons/toucan.jpg",
      "title": "Le Tocan (Toucan)",
      "author": "Jacques Barraband (Histoire naturelle des perroquets)",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barraband_No3_Le_Tocan.jpg"
    },
    {
      "src": "/icons/met/363843.jpg",
      "title": "Eclectus Roratus Polychloros",
      "author": "Edward Lear",
      "medium": "Watercolor and gouache over graphite",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/363843"
    }
  ],
  "nyc-traffic": [
    {
      "src": "/icons/met/339882.jpg",
      "title": "Sleighing in New York",
      "author": "Thomas Benecke",
      "medium": "Color lithograph with hand-coloring",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/339882"
    },
    {
      "src": "/icons/met/388212.jpg",
      "title": "Broadway Circus and Olympic Theatre, Broadway between Howard and Grand Streets, New York",
      "author": "Anonymous, American, 19th century",
      "medium": "Watercolor and ink",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/388212"
    },
    {
      "src": "/icons/met/266296.jpg",
      "title": "Mulberry Street",
      "author": "Sid Grossman",
      "medium": "Gelatin silver print",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/266296"
    }
  ],
  "nyc-breeze": [
    {
      "src": "/icons/met/13115.jpg",
      "title": "New York from the Heights near Brooklyn",
      "author": "William Guy Wall",
      "medium": "Watercolor and graphite on white wove paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/13115"
    },
    {
      "src": "/icons/met/488326.jpg",
      "title": "Brooklyn Bridge",
      "author": "John Marin",
      "medium": "Watercolor and charcoal on paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/488326"
    },
    {
      "src": "/icons/met/853645.jpg",
      "title": "Rooftops, Brooklyn",
      "author": "Fidelia Bridges",
      "medium": "Watercolor and gouache on tan hot-pressed paper",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/853645"
    }
  ],
  "nyc-park": [
    {
      "src": "/icons/met/371952.jpg",
      "title": "Central Park (Summer)",
      "author": "Julius Bien",
      "medium": "Lithograph, printed in colors",
      "license": "CC0 (The Metropolitan Museum of Art)",
      "sourceUrl": "https://www.metmuseum.org/art/collection/search/371952",
      "detailSrc": "https://images.metmuseum.org/CRDImages/dp/original/MM22125.jpg"
    }
  ]
};

export const soundPoolMap: Record<string, string> = {
  "surf": "surf",
  "wind": "wind",
  "wind-forest": "wind",
  "forest-ambience": "forest",
  "rain": "rain",
  "stream": "stream",
  "quetzal": "quetzal",
  "toucan": "toucan"
};

export const artworkAttributions: ArtworkAttribution[] = [
  { file: '/icons/gray-catbird.jpg', title: 'Cat-Bird, 1. Male 2. Female (Plant Black-berry, Rubus villosus.), No. 28, Pl. 140', author: 'John James Audubon; lith. W. Endicott & Co. From The New York Public Library.', license: 'Public domain (NYPL: no known U.S. copyright restrictions). Credit: From The New York Public Library.', sourceUrl: 'https://digitalcollections.nypl.org/items/2a28c850-c5f9-012f-9b77-58d385a7bc34' },
  { file: '/icons/northern-cardinal.jpg', title: 'Common Cardinal Grosbeak, 1. Male 2. Female (Wild Almond Prunus caroliniana), No. 41, Pl. 203', author: 'John James Audubon; lith., printed & col. J. T. Bowen, Phila. From The New York Public Library.', license: 'Public domain (NYPL: no known U.S. copyright restrictions). Credit: From The New York Public Library.', sourceUrl: 'https://digitalcollections.nypl.org/items/43a68310-c5f9-012f-0599-58d385a7bc34' },
  { file: '/icons/blue-jay.jpg', title: 'Blue Jay, 1. Male 2. & 3. Female (Trumpet flower, Bignonia radicans.), Pl. 231', author: 'John James Audubon; lith., printed & col. J. T. Bowen, Phila. From The New York Public Library.', license: 'Public domain (NYPL: no known U.S. copyright restrictions). Credit: From The New York Public Library.', sourceUrl: 'https://digitalcollections.nypl.org/items/510d47d9-7308-a3d9-e040-e00a18064a99' },
  { file: '/icons/tui.jpg', title: 'Tui adult and young', author: 'John Gerrard Keulemans (Walter Buller, A History of the Birds of New Zealand)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tui_adult_and_young.jpg' },
  { file: '/icons/bellbird.jpg', title: 'New Zealand Bellbird (Anthornis melanura)', author: 'John Gerrard Keulemans (Buller, 1888)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bul01BirdP009_(cropped).jpg' },
  { file: '/icons/morepork.jpg', title: 'Morepork (Ruru) and Laughing owl (Whekau)', author: 'John Gerrard Keulemans (Buller, 1888)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Morepork_(Ruru)_and_Laughing_owl_(Whekau).jpg' },
  { file: '/icons/fantail.jpg', title: 'Fantails (Rhipidura)', author: 'John Gerrard Keulemans (Buller)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bullers_fantails.jpg' },
  { file: '/icons/gull.jpg', title: 'Red-billed gull (Chroicocephalus scopulinus)', author: 'John Gerrard Keulemans (Buller, 1905)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bul02BirdP029.jpg' },
  { file: '/icons/toucan.jpg', title: 'Le Tocan (Toucan)', author: 'Jacques Barraband (Histoire naturelle des perroquets)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Barraband_No3_Le_Tocan.jpg' },
  { file: '/icons/howler.jpg', title: 'Red howler monkey (Mycetes seniculus)', author: 'Iconographia Zoologica (University of Amsterdam, 1863)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mycetes_seniculus_-_1863_-_Print_-_Iconographia_Zoologica_-_Special_Collections_University_of_Amsterdam_-_UBA01_IZ20200132.tif' },
  { file: '/icons/insects.jpg', title: 'Metamorphosis of a Small Emperor Moth on a Damson Plum (plate 13)', author: 'Maria Sibylla Merian (Getty Museum)', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Metamorphosis_of_a_Small_Emperor_Moth_on_a_Damson_Plum,_plate_13_of_the_Caterpillar_Book,_by_Maria_Sibylla_Merian_(Getty_109Q5N).jpg' },
  { file: '/icons/met/11908.jpg', title: 'Good Harbor Beach, Cape Ann, Massachusetts', author: 'William Trost Richards — Graphite on tan wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/11908' },
  { file: '/icons/met/17053.jpg', title: 'Boys in a Dory', author: 'Winslow Homer — Watercolor and gouache over graphite', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/17053' },
  { file: '/icons/met/339153.jpg', title: 'Fishing Boats on the Beach in Winter', author: 'Anton Mauve — Black chalk, watercolor, and white bodycolor', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/339153' },
  { file: '/icons/met/334086.jpg', title: 'On the Beach', author: 'Eugène Boudin — Graphite and watercolor', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/334086' },
  { file: '/icons/met/460052.jpg', title: 'Beach Scene', author: 'Eugène Boudin — Pastel on gray wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/460052' },
  { file: '/icons/met/15519.jpg', title: 'Bay, Hill, and Figure on Shore (from Sketchbook X)', author: 'William Trost Richards — Graphite on off-white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/15519' },
  { file: '/icons/met/824771.jpg', title: 'Marie Antoinette in a Park', author: 'Anonymous (French) — Black chalk, stumped, and white chalk', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/824771' },
  { file: '/icons/met/11306.jpg', title: 'Birch Tree, Niagara', author: 'John Frederick Kensett — Graphite on smooth textured off-white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/11306' },
  { file: '/icons/met/11124.jpg', title: 'Hurricane, Bahamas', author: 'Winslow Homer — Watercolor and graphite on off-white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/11124' },
  { file: '/icons/met/10378.jpg', title: 'Forest Scene', author: 'Johann Hermann Carmiencke — Graphite and watercolor on buff-colored wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/10378' },
  { file: '/icons/met/11306.jpg', title: 'Birch Tree, Niagara', author: 'John Frederick Kensett — Graphite on smooth textured off-white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/11306' },
  { file: '/icons/met/15775.jpg', title: 'Two Sketches: River Bank with Trees; Figure in a Canoe', author: 'Albert Bierstadt — Graphite on wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/15775' },
  { file: '/icons/met/11124.jpg', title: 'Hurricane, Bahamas', author: 'Winslow Homer — Watercolor and graphite on off-white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/11124' },
  { file: '/icons/met/13115.jpg', title: 'New York from the Heights near Brooklyn', author: 'William Guy Wall — Watercolor and graphite on white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/13115' },
  { file: '/icons/met/489985.jpg', title: 'Rain Landscape', author: 'Vasily Kandinsky — Watercolor over graphite on paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/489985' },
  { file: '/icons/met/15775.jpg', title: 'Two Sketches: River Bank with Trees; Figure in a Canoe', author: 'Albert Bierstadt — Graphite on wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/15775' },
  { file: '/icons/met/17053.jpg', title: 'Boys in a Dory', author: 'Winslow Homer — Watercolor and gouache over graphite', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/17053' },
  { file: '/icons/met/15519.jpg', title: 'Bay, Hill, and Figure on Shore (from Sketchbook X)', author: 'William Trost Richards — Graphite on off-white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/15519' },
  { file: '/icons/met/338617.jpg', title: 'Long-Tailed Bird Seen in Profile', author: 'Count Giorgio Durante (Duranti) — Watercolor over graphite', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/338617' },
  { file: '/icons/met/363843.jpg', title: 'Eclectus Roratus Polychloros', author: 'Edward Lear — Watercolor and gouache over graphite', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/363843' },
  { file: '/icons/met/363843.jpg', title: 'Eclectus Roratus Polychloros', author: 'Edward Lear — Watercolor and gouache over graphite', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/363843' },
  { file: '/icons/met/339882.jpg', title: 'Sleighing in New York', author: 'Thomas Benecke — Color lithograph with hand-coloring', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/339882' },
  { file: '/icons/met/388212.jpg', title: 'Broadway Circus and Olympic Theatre, Broadway between Howard and Grand Streets, New York', author: 'Anonymous, American, 19th century — Watercolor and ink', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/388212' },
  { file: '/icons/met/266296.jpg', title: 'Mulberry Street', author: 'Sid Grossman — Gelatin silver print', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/266296' },
  { file: '/icons/met/13115.jpg', title: 'New York from the Heights near Brooklyn', author: 'William Guy Wall — Watercolor and graphite on white wove paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/13115' },
  { file: '/icons/met/488326.jpg', title: 'Brooklyn Bridge', author: 'John Marin — Watercolor and charcoal on paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/488326' },
  { file: '/icons/met/853645.jpg', title: 'Rooftops, Brooklyn', author: 'Fidelia Bridges — Watercolor and gouache on tan hot-pressed paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/853645' },
  { file: '/icons/met/19239.jpg', title: 'Central Park', author: 'Robert Henri — Watercolor on paper', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/19239' },
  { file: '/icons/met/371952.jpg', title: 'Central Park (Summer)', author: 'Julius Bien — Lithograph, printed in colors', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/371952' },
  { file: '/icons/met/11804.jpg', title: 'Central Park', author: 'Maurice Brazil Prendergast — Oil on canvas', license: 'CC0 (The Metropolitan Museum of Art)', sourceUrl: 'https://www.metmuseum.org/art/collection/search/11804' },
];
