// AUTO-GENERATED by scripts/download-audio-variants.mjs — do not edit by hand.
// Each entry is one openly-licensed audio clip with its required attribution.
import type { SoundClip } from './types';

export const soundClips: SoundClip[] = [
  {
    "id": "bells-4-church",
    "type": "bells",
    "tags": [
      "european"
    ],
    "sustained": false,
    "src": "/audio/pool/bells/bells-4-church.mp3",
    "title": "4 church bells",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/4-church-bells-s0829.html"
  },
  {
    "id": "bells-bronze",
    "type": "bells",
    "tags": [
      "temple"
    ],
    "sustained": false,
    "src": "/audio/pool/bells/bells-bronze.mp3",
    "title": "Bronze bell #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/bronze-bell-1-s2703.html"
  },
  {
    "id": "bells-church",
    "type": "bells",
    "tags": [
      "european",
      "urban"
    ],
    "sustained": false,
    "src": "/audio/pool/bells/bells-church.mp3",
    "title": "Church bell",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/church-bell-s0135.html"
  },
  {
    "id": "bells-tibetan",
    "type": "bells",
    "tags": [
      "asian",
      "temple",
      "calm"
    ],
    "sustained": false,
    "src": "/audio/pool/bells/bells-tibetan.mp3",
    "title": "Tibetan bowl, singing",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/tibetan-bowl-singing-s1109.html"
  },
  {
    "id": "city-cheerful-street",
    "type": "city-hum",
    "tags": [
      "urban",
      "european"
    ],
    "sustained": true,
    "src": "/audio/pool/city-hum/city-cheerful-street.mp3",
    "title": "Cheerful street",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/cheerful-street-s2372.html"
  },
  {
    "id": "city-pedestrian",
    "type": "city-hum",
    "tags": [
      "urban",
      "european",
      "calm"
    ],
    "sustained": true,
    "src": "/audio/pool/city-hum/city-pedestrian.mp3",
    "title": "Small pedestrian street",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/small-pedestrian-street-s0527.html"
  },
  {
    "id": "city-street-roads",
    "type": "city-hum",
    "tags": [
      "urban",
      "temperate"
    ],
    "sustained": true,
    "src": "/audio/pool/city-hum/city-street-roads.mp3",
    "title": "Street and roads",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/street-and-roads-s0608.html"
  },
  {
    "id": "legacy-blue-jay",
    "type": "corvid",
    "tags": [
      "temperate",
      "americas"
    ],
    "sustained": false,
    "src": "/audio/bed-stuy/blue-jay.ogg",
    "title": "Blue Jay call (XC86756)",
    "author": "Jonathon Jongsma / Xeno-canto",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cyanocitta_cristata_-_Blue_Jay_-_XC86756.ogg"
  },
  {
    "id": "fire-branching-1",
    "type": "fire",
    "tags": [
      "camp",
      "rural"
    ],
    "sustained": true,
    "src": "/audio/pool/fire/fire-branching-1.mp3",
    "title": "Big branching fire #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/big-branching-fire-1-s0987.html"
  },
  {
    "id": "fire-fireplace",
    "type": "fire",
    "tags": [
      "cold",
      "indoor"
    ],
    "sustained": true,
    "src": "/audio/pool/fire/fire-fireplace.mp3",
    "title": "Fireplace #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/fireplace-1-s0030.html"
  },
  {
    "id": "forest-1",
    "type": "forest",
    "tags": [
      "temperate",
      "woodland"
    ],
    "sustained": true,
    "src": "/audio/pool/forest/forest-1.mp3",
    "title": "Forest",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/forest-s0100.html"
  },
  {
    "id": "forest-3",
    "type": "forest",
    "tags": [
      "temperate",
      "woodland"
    ],
    "sustained": true,
    "src": "/audio/pool/forest/forest-3.mp3",
    "title": "Forest #3",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/forest-3-s2715.html"
  },
  {
    "id": "forest-night-rain",
    "type": "forest",
    "tags": [
      "temperate",
      "night",
      "woodland"
    ],
    "sustained": true,
    "src": "/audio/pool/forest/forest-night-rain.mp3",
    "title": "Forest at night after rain",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/forest-at-night-after-rain-s0555.html"
  },
  {
    "id": "forest-rambouillet",
    "type": "forest",
    "tags": [
      "temperate",
      "european",
      "woodland"
    ],
    "sustained": true,
    "src": "/audio/pool/forest/forest-rambouillet.mp3",
    "title": "Rambouillet forest",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/rambouillet-forest-s0136.html"
  },
  {
    "id": "legacy-forest-ambience",
    "type": "forest",
    "tags": [
      "temperate",
      "woodland"
    ],
    "sustained": true,
    "src": "/audio/nz/forest-ambience.mp3",
    "title": "Forest",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/forest-s0100.html"
  },
  {
    "id": "frogs-1",
    "type": "frogs",
    "tags": [
      "wetland",
      "night"
    ],
    "sustained": true,
    "src": "/audio/pool/frogs/frogs-1.mp3",
    "title": "Frogs #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/frogs-1-s0997.html"
  },
  {
    "id": "frogs-2",
    "type": "frogs",
    "tags": [
      "wetland",
      "tropical",
      "night"
    ],
    "sustained": true,
    "src": "/audio/pool/frogs/frogs-2.mp3",
    "title": "Frogs #2",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/frogs-2-s0998.html"
  },
  {
    "id": "insects-cicada-1",
    "type": "insects",
    "tags": [
      "summer",
      "mediterranean"
    ],
    "sustained": true,
    "src": "/audio/pool/insects/insects-cicada-1.mp3",
    "title": "Cicada #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/cicada-1-s2246.html"
  },
  {
    "id": "insects-cicadas",
    "type": "insects",
    "tags": [
      "summer",
      "tropical"
    ],
    "sustained": true,
    "src": "/audio/pool/insects/insects-cicadas.mp3",
    "title": "Cicadas",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/cicadas-s3002.html"
  },
  {
    "id": "insects-field-cricket",
    "type": "insects",
    "tags": [
      "temperate",
      "rural",
      "summer"
    ],
    "sustained": true,
    "src": "/audio/pool/insects/insects-field-cricket.mp3",
    "title": "Field cricket",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/field-cricket-s1020.html"
  },
  {
    "id": "insects-nocturnal",
    "type": "insects",
    "tags": [
      "tropical",
      "night",
      "summer"
    ],
    "sustained": true,
    "src": "/audio/pool/insects/insects-nocturnal.mp3",
    "title": "Nocturnal insects #4",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/nocturnal-insects-4-s1470.html"
  },
  {
    "id": "insects-singing-1",
    "type": "insects",
    "tags": [
      "summer",
      "night"
    ],
    "sustained": true,
    "src": "/audio/pool/insects/insects-singing-1.mp3",
    "title": "Singing insect #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/singing-insect-1-s3089.html"
  },
  {
    "id": "legacy-insect-chorus",
    "type": "insects",
    "tags": [
      "tropical",
      "night"
    ],
    "sustained": true,
    "src": "/audio/costa-rica/insect-chorus.mp3",
    "title": "Nocturnal Insects #4",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/nocturnal-insects-4-s1470.html"
  },
  {
    "id": "jazz-its-a-thing",
    "type": "jazz",
    "tags": [
      "jazz",
      "music",
      "upbeat"
    ],
    "sustained": true,
    "src": "/audio/pool/jazz/jazz-its-a-thing.ogg",
    "title": "It's a jazz thing",
    "author": "smiling cynic (Wikimedia Commons)",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:It's a jazz thing.ogg"
  },
  {
    "id": "jazz-kinda-sorta",
    "type": "jazz",
    "tags": [
      "jazz",
      "music",
      "mellow"
    ],
    "sustained": true,
    "src": "/audio/pool/jazz/jazz-kinda-sorta.ogg",
    "title": "Kinda sorta",
    "author": "smiling cynic (Wikimedia Commons)",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kinda sorta.ogg"
  },
  {
    "id": "jazz-park",
    "type": "jazz",
    "tags": [
      "jazz",
      "music",
      "mellow"
    ],
    "sustained": true,
    "src": "/audio/pool/jazz/jazz-park.ogg",
    "title": "Jazz at the park",
    "author": "Manwithmetalpig (Wikimedia Commons)",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jazz at the park.ogg"
  },
  {
    "id": "jazz-sleepless",
    "type": "jazz",
    "tags": [
      "jazz",
      "music",
      "mellow",
      "late-night"
    ],
    "sustained": true,
    "src": "/audio/pool/jazz/jazz-sleepless.ogg",
    "title": "Dream a sleepless dream",
    "author": "smiling cynic (Wikimedia Commons)",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dream a sleepless dream.ogg"
  },
  {
    "id": "jazz-what-can-i-say",
    "type": "jazz",
    "tags": [
      "jazz",
      "music",
      "upbeat"
    ],
    "sustained": true,
    "src": "/audio/pool/jazz/jazz-what-can-i-say.ogg",
    "title": "What can i say",
    "author": "smiling cynic (Wikimedia Commons)",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:What can i say.ogg"
  },
  {
    "id": "market-covered-1",
    "type": "market",
    "tags": [
      "urban",
      "european"
    ],
    "sustained": true,
    "src": "/audio/pool/market/market-covered-1.mp3",
    "title": "Covered market #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/covered-market-1-s3346.html"
  },
  {
    "id": "market-crowd",
    "type": "market",
    "tags": [
      "urban"
    ],
    "sustained": true,
    "src": "/audio/pool/market/market-crowd.mp3",
    "title": "Crowd of 50-60 people #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/crowd-of-50-60-people-1-s3515.html"
  },
  {
    "id": "market-spanish-crowd",
    "type": "market",
    "tags": [
      "urban",
      "european",
      "mediterranean"
    ],
    "sustained": true,
    "src": "/audio/pool/market/market-spanish-crowd.mp3",
    "title": "Spanish crowd",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/spanish-crowd-s0825.html"
  },
  {
    "id": "legacy-morepork",
    "type": "owl",
    "tags": [
      "pacific",
      "nz",
      "night"
    ],
    "sustained": false,
    "src": "/audio/nz/morepork-call.ogg",
    "title": "Pacific Pygmy Owl call",
    "author": "Wikimedia Commons contributor",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pacific_Pygmy_Owl_call_(Glaucidium_peruanum).ogg"
  },
  {
    "id": "owl-barn",
    "type": "owl",
    "tags": [
      "temperate",
      "night",
      "rural"
    ],
    "sustained": false,
    "src": "/audio/pool/owl/owl-barn.mp3",
    "title": "Barn owl",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/barn-owl-s1400.html"
  },
  {
    "id": "owl-night-birds",
    "type": "owl",
    "tags": [
      "night",
      "woodland"
    ],
    "sustained": true,
    "src": "/audio/pool/owl/owl-night-birds.mp3",
    "title": "Birds at night",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/birds-at-night-s0315.html"
  },
  {
    "id": "owl-tawny-1",
    "type": "owl",
    "tags": [
      "temperate",
      "night",
      "european"
    ],
    "sustained": false,
    "src": "/audio/pool/owl/owl-tawny-1.mp3",
    "title": "Tawny owl #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/tawny-owl-1-s1763.html"
  },
  {
    "id": "owl-tawny-2",
    "type": "owl",
    "tags": [
      "temperate",
      "night",
      "woodland"
    ],
    "sustained": false,
    "src": "/audio/pool/owl/owl-tawny-2.mp3",
    "title": "Tawny owl #2",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/tawny-owl-2-s1764.html"
  },
  {
    "id": "legacy-howler",
    "type": "primates",
    "tags": [
      "tropical",
      "jungle"
    ],
    "sustained": true,
    "src": "/audio/costa-rica/howler-distant.mp3",
    "title": "Hall of the monkeys (primate ambience)",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/hall-of-the-monkeys-of-the-menagerie-of-paris-s1004.html"
  },
  {
    "id": "legacy-rain-canopy",
    "type": "rain",
    "tags": [
      "tropical",
      "storm"
    ],
    "sustained": true,
    "src": "/audio/costa-rica/rain-canopy.mp3",
    "title": "Rain and Thunder #20",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/storm-and-rain-4-s2719.html"
  },
  {
    "id": "rain-concrete",
    "type": "rain",
    "tags": [
      "urban"
    ],
    "sustained": true,
    "src": "/audio/pool/rain/rain-concrete.mp3",
    "title": "Rain on concrete",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/rain-on-concrete-s1289.html"
  },
  {
    "id": "rain-light",
    "type": "rain",
    "tags": [
      "temperate",
      "calm"
    ],
    "sustained": true,
    "src": "/audio/pool/rain/rain-light.ogg",
    "title": "Sound of light rainfall",
    "author": "Mijesty (Wikimedia Commons)",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sound_of_light_rainfall.ogg"
  },
  {
    "id": "rain-storm-2",
    "type": "rain",
    "tags": [
      "storm",
      "tropical"
    ],
    "sustained": true,
    "src": "/audio/pool/rain/rain-storm-2.mp3",
    "title": "Rain and storm #2",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/rain-and-storm-2-s0740.html"
  },
  {
    "id": "rain-terrace",
    "type": "rain",
    "tags": [
      "urban",
      "temperate",
      "summer"
    ],
    "sustained": true,
    "src": "/audio/pool/rain/rain-terrace.mp3",
    "title": "Summer rain on terrace",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/summer-rain-on-terrace-s1019.html"
  },
  {
    "id": "rain-umbrella",
    "type": "rain",
    "tags": [
      "urban",
      "temperate"
    ],
    "sustained": true,
    "src": "/audio/pool/rain/rain-umbrella.mp3",
    "title": "Rain under an umbrella",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/rain-under-an-umbrella-s2679.html"
  },
  {
    "id": "legacy-gull",
    "type": "seabird",
    "tags": [
      "coastal",
      "european"
    ],
    "sustained": true,
    "src": "/audio/nz/gull-call.ogg",
    "title": "Herring Gull",
    "author": "British Library / Wikimedia Commons",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Herring_Gull_(Larus_argentatus)_(W1CDR0001420_BD12).ogg"
  },
  {
    "id": "seabird-gulls-harbour",
    "type": "seabird",
    "tags": [
      "coastal",
      "harbour"
    ],
    "sustained": true,
    "src": "/audio/pool/seabird/seabird-gulls-harbour.mp3",
    "title": "Gulls on the harbour",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/gulls-on-the-harbor-s2573.html"
  },
  {
    "id": "seabird-waves-gulls",
    "type": "seabird",
    "tags": [
      "coastal",
      "beach"
    ],
    "sustained": true,
    "src": "/audio/pool/seabird/seabird-waves-gulls.mp3",
    "title": "Sea waves and seagulls",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/sea-waves-and-seagulls-s0267.html"
  },
  {
    "id": "legacy-bellbird",
    "type": "songbird",
    "tags": [
      "pacific",
      "nz",
      "native"
    ],
    "sustained": true,
    "src": "/audio/nz/bellbird-loop.ogg",
    "title": "New Zealand Bellbird",
    "author": "Wikimedia Commons contributor",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:New_Zealand_Bellbird_(Anthornis_melanura).ogg"
  },
  {
    "id": "legacy-blackbird",
    "type": "songbird",
    "tags": [
      "temperate",
      "european",
      "garden"
    ],
    "sustained": true,
    "src": "/audio/nz/fantail-loop.ogg",
    "title": "Common Blackbird song",
    "author": "British Library / Wikimedia Commons",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Common_Blackbird_song_(Turdus_merula).ogg"
  },
  {
    "id": "legacy-cardinal",
    "type": "songbird",
    "tags": [
      "temperate",
      "americas",
      "garden"
    ],
    "sustained": true,
    "src": "/audio/bed-stuy/northern-cardinal.ogg",
    "title": "Northern Cardinal song (XC125284)",
    "author": "Xeno-canto / Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cardinalis_cardinalis_-_Northern_Cardinal_XC125284.ogg"
  },
  {
    "id": "legacy-catbird",
    "type": "songbird",
    "tags": [
      "temperate",
      "americas",
      "garden"
    ],
    "sustained": true,
    "src": "/audio/bed-stuy/gray-catbird.ogg",
    "title": "Gray Catbird",
    "author": "G. McGrane",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gray_Catbird.ogg"
  },
  {
    "id": "legacy-tui",
    "type": "songbird",
    "tags": [
      "pacific",
      "nz",
      "native"
    ],
    "sustained": true,
    "src": "/audio/nz/tui-loop.ogg",
    "title": "Tui song — Trelissick Park",
    "author": "Wikimedia Commons contributor",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tui_song_-_Trelissick_Park_-8_March_2021.ogg"
  },
  {
    "id": "songbird-blackbird-10",
    "type": "songbird",
    "tags": [
      "temperate",
      "european",
      "woodland"
    ],
    "sustained": true,
    "src": "/audio/pool/songbird/songbird-blackbird-10.mp3",
    "title": "Common blackbird #10",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/common-blackbird-10-s3483.html"
  },
  {
    "id": "songbird-blackbird-2",
    "type": "songbird",
    "tags": [
      "temperate",
      "european",
      "garden"
    ],
    "sustained": true,
    "src": "/audio/pool/songbird/songbird-blackbird-2.mp3",
    "title": "Common blackbird #2",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/common-blackbird-2-s3474.html"
  },
  {
    "id": "songbird-blackbird-5",
    "type": "songbird",
    "tags": [
      "temperate",
      "european",
      "garden"
    ],
    "sustained": true,
    "src": "/audio/pool/songbird/songbird-blackbird-5.mp3",
    "title": "Common blackbird #5",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/common-blackbird-5-s3478.html"
  },
  {
    "id": "songbird-breeze-birds",
    "type": "songbird",
    "tags": [
      "temperate",
      "garden",
      "dawn"
    ],
    "sustained": true,
    "src": "/audio/pool/songbird/songbird-breeze-birds.ogg",
    "title": "Gentle breeze and birds singing",
    "author": "ezwa (Wikimedia Commons)",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gentle_breeze_and_birds_singing.ogg"
  },
  {
    "id": "legacy-stream-distant",
    "type": "stream",
    "tags": [
      "forest"
    ],
    "sustained": true,
    "src": "/audio/costa-rica/stream-distant.mp3",
    "title": "Forest and Stream #1",
    "author": "Pierre SIBANARCO — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/forest-and-stream-1-s2713.html"
  },
  {
    "id": "stream-brooklet",
    "type": "stream",
    "tags": [
      "forest",
      "temperate",
      "calm"
    ],
    "sustained": true,
    "src": "/audio/pool/stream/stream-brooklet.mp3",
    "title": "Brooklet",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/brooklet-s0864.html"
  },
  {
    "id": "stream-flow",
    "type": "stream",
    "tags": [
      "temperate",
      "calm"
    ],
    "sustained": true,
    "src": "/audio/pool/stream/stream-flow.mp3",
    "title": "Water flow #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/water-flow-1-s0204.html"
  },
  {
    "id": "stream-small-1",
    "type": "stream",
    "tags": [
      "forest",
      "temperate"
    ],
    "sustained": true,
    "src": "/audio/pool/stream/stream-small-1.mp3",
    "title": "Small stream #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/small-stream-1-s0213.html"
  },
  {
    "id": "stream-watercourse-1",
    "type": "stream",
    "tags": [
      "mountain",
      "alpine"
    ],
    "sustained": true,
    "src": "/audio/pool/stream/stream-watercourse-1.mp3",
    "title": "Watercourse #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/watercourse-1-s3132.html"
  },
  {
    "id": "stream-waterfall",
    "type": "stream",
    "tags": [
      "forest",
      "mountain"
    ],
    "sustained": true,
    "src": "/audio/pool/stream/stream-waterfall.mp3",
    "title": "Small waterfall #2",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/small-waterfall-2-s0219.html"
  },
  {
    "id": "thunder-1",
    "type": "thunder",
    "tags": [
      "storm"
    ],
    "sustained": false,
    "src": "/audio/pool/thunder/thunder-1.mp3",
    "title": "Thunder",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/thunder-s2718.html"
  },
  {
    "id": "thunder-2",
    "type": "thunder",
    "tags": [
      "storm"
    ],
    "sustained": false,
    "src": "/audio/pool/thunder/thunder-2.mp3",
    "title": "Thunder #2",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/thunder-2-s3113.html"
  },
  {
    "id": "thunder-6",
    "type": "thunder",
    "tags": [
      "storm",
      "tropical"
    ],
    "sustained": false,
    "src": "/audio/pool/thunder/thunder-6.mp3",
    "title": "Thunder #6",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/thunder-6-s3179.html"
  },
  {
    "id": "traffic-children-street",
    "type": "traffic",
    "tags": [
      "urban"
    ],
    "sustained": true,
    "src": "/audio/pool/traffic/traffic-children-street.mp3",
    "title": "Children in the street",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/children-in-the-street-s0370.html"
  },
  {
    "id": "legacy-quetzal",
    "type": "tropical-bird",
    "tags": [
      "tropical",
      "cloud-forest"
    ],
    "sustained": true,
    "src": "/audio/costa-rica/quetzal-song.ogg",
    "title": "Resplendent Quetzal song",
    "author": "Wikimedia Commons contributor",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Resplendent_Quetzal_song_(Pharomachrus_mocinno).ogg"
  },
  {
    "id": "legacy-toucan",
    "type": "tropical-bird",
    "tags": [
      "tropical",
      "jungle"
    ],
    "sustained": false,
    "src": "/audio/costa-rica/toucan-call.ogg",
    "title": "Toco Toucan call",
    "author": "Wikimedia Commons contributor",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Toco_Toucan_call_(Ramphastos_toco).ogg"
  },
  {
    "id": "legacy-surf",
    "type": "waves",
    "tags": [
      "coastal"
    ],
    "sustained": true,
    "src": "/audio/nz/surf-loop.ogg",
    "title": "Adriatic Sea waves",
    "author": "Wikimedia Commons contributor",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Adriatic_Sea_waves.ogg"
  },
  {
    "id": "waves-agitated",
    "type": "waves",
    "tags": [
      "coastal",
      "storm"
    ],
    "sustained": true,
    "src": "/audio/pool/waves/waves-agitated.mp3",
    "title": "Slightly agitated sea",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/slightly-agitated-sea-s0915.html"
  },
  {
    "id": "waves-beach-sea",
    "type": "waves",
    "tags": [
      "coastal",
      "beach"
    ],
    "sustained": true,
    "src": "/audio/pool/waves/waves-beach-sea.mp3",
    "title": "Beach and sea",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/beach-and-sea-s1059.html"
  },
  {
    "id": "waves-crashing",
    "type": "waves",
    "tags": [
      "coastal",
      "storm"
    ],
    "sustained": true,
    "src": "/audio/pool/waves/waves-crashing.ogg",
    "title": "Oceanwavescrushing",
    "author": "Luftrum (Wikimedia Commons)",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oceanwavescrushing.ogg"
  },
  {
    "id": "waves-pebble",
    "type": "waves",
    "tags": [
      "coastal",
      "beach",
      "calm"
    ],
    "sustained": true,
    "src": "/audio/pool/waves/waves-pebble.ogg",
    "title": "On a pebble beach",
    "author": "earthcalling (Wikimedia Commons)",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:On_a_pebble_beach.ogg"
  },
  {
    "id": "waves-sea",
    "type": "waves",
    "tags": [
      "coastal",
      "temperate"
    ],
    "sustained": true,
    "src": "/audio/pool/waves/waves-sea.mp3",
    "title": "Sea waves",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/sea-waves-s0266.html"
  },
  {
    "id": "waves-small-beach",
    "type": "waves",
    "tags": [
      "coastal",
      "beach",
      "calm"
    ],
    "sustained": true,
    "src": "/audio/pool/waves/waves-small-beach.mp3",
    "title": "Beach, small waves",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/beach-small-waves-s0265.html"
  },
  {
    "id": "legacy-wind",
    "type": "wind",
    "tags": [
      "temperate",
      "open"
    ],
    "sustained": true,
    "src": "/audio/nz/wind-loop.mp3",
    "title": "Wind",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/wind-s0595.html"
  },
  {
    "id": "wind-howling",
    "type": "wind",
    "tags": [
      "cold",
      "storm",
      "alpine"
    ],
    "sustained": true,
    "src": "/audio/pool/wind/wind-howling.ogg",
    "title": "Howling wind",
    "author": "Tvabutzku1234 (Wikimedia Commons)",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Howling_wind.ogg"
  },
  {
    "id": "wind-in-tree",
    "type": "wind",
    "tags": [
      "forest",
      "temperate"
    ],
    "sustained": true,
    "src": "/audio/pool/wind/wind-in-tree.mp3",
    "title": "Wind in a tree",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/wind-in-a-tree-s0659.html"
  },
  {
    "id": "wind-open",
    "type": "wind",
    "tags": [
      "temperate",
      "open"
    ],
    "sustained": true,
    "src": "/audio/pool/wind/wind-open.mp3",
    "title": "Wind",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/wind-s0595.html"
  },
  {
    "id": "wind-strong-1",
    "type": "wind",
    "tags": [
      "coastal",
      "open",
      "storm"
    ],
    "sustained": true,
    "src": "/audio/pool/wind/wind-strong-1.mp3",
    "title": "Strong wind #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/strong-wind-1-s0146.html"
  },
  {
    "id": "wind-tall-grass",
    "type": "wind",
    "tags": [
      "open",
      "temperate",
      "rural"
    ],
    "sustained": true,
    "src": "/audio/pool/wind/wind-tall-grass.mp3",
    "title": "Wind in tall grass",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/wind-in-tall-grass-s0908.html"
  },
  {
    "id": "wind-trees-1",
    "type": "wind",
    "tags": [
      "forest",
      "temperate"
    ],
    "sustained": true,
    "src": "/audio/pool/wind/wind-trees-1.mp3",
    "title": "Strong wind and trees #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/strong-wind-and-trees-1-s1450.html"
  },
  {
    "id": "wind-whistling",
    "type": "wind",
    "tags": [
      "alpine",
      "cold",
      "open"
    ],
    "sustained": true,
    "src": "/audio/pool/wind/wind-whistling.mp3",
    "title": "Whistling of the wind #1",
    "author": "Joseph SARDIN — BigSoundBank.com",
    "license": "CC0 1.0",
    "sourceUrl": "https://bigsoundbank.com/whistling-of-the-wind-1-s0147.html"
  }
];
